server:
  port: 8000
  servlet:
    context-path: /fn

swagger:
  title: SpringBoot学习
  description: SpringBoot快速入门
  version: 1.0.0
  name: 吴钦飞
  url: http://www.baidu.com
  email: wuqinfei@qq.comSwaggerConfig

spring:
  datasource:
    username: root
    password: wuqinfei@qq.com
    url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=UTC&useUnicode=true&CharacterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  resources:
    static-locations: classpath:/frondend/dist/
  thymeleaf:
    prefix: classpath:/frondend/dist/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    cache: false
    servlet:
      content-type: text/html

mybatis:
  type-aliases-package: com.fn.sb.hello.*.pojo
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  configuration:
    # `user_id` <=> userId
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl




